# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_redirect', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='redirect',
            name='language',
            field=models.CharField(default='en', max_length=255),
        ),
    ]
