# Generated by Django 3.1.4 on 2021-05-02 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_redirect', '0003_auto_20190810_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redirect',
            name='new_path',
            field=models.CharField(blank=True, help_text='Select a Page or write an url', max_length=512, verbose_name='redirect to'),
        ),
    ]
