# Generated by Django 3.1.4 on 2021-05-14 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_redirect', '0004_auto_20210502_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redirect',
            name='new_path',
            field=models.CharField(blank=True, help_text='Select a Page or write an url', max_length=700, verbose_name='redirect to'),
        ),
    ]
