# Generated by Django 3.2.17 on 2023-08-31 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_redirect', '0005_auto_20210514_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='redirect',
            name='de_path',
            field=models.CharField(blank=True, help_text='Select a Page or write an url', max_length=700, verbose_name='redirect to (de)'),
        ),
        migrations.AddField(
            model_name='redirect',
            name='default_path',
            field=models.CharField(blank=True, help_text='Select a Page or write an url', max_length=700, verbose_name='redirect to (default)'),
        ),
        migrations.AddField(
            model_name='redirect',
            name='en_path',
            field=models.CharField(blank=True, help_text='Select a Page or write an url', max_length=700, verbose_name='redirect to (en)'),
        ),
        migrations.AddField(
            model_name='redirect',
            name='fr_path',
            field=models.CharField(blank=True, help_text='Select a Page or write an url', max_length=700, verbose_name='redirect to (fr)'),
        ),
        migrations.AddField(
            model_name='redirect',
            name='it_path',
            field=models.CharField(blank=True, help_text='Select a Page or write an url', max_length=700, verbose_name='redirect to (it)'),
        ),
    ]
